[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "jakis_dlugi_losowy_secret"

[auth.microsoft]
client_id = "TWOJ_CLIENT_ID"
client_secret = "TWOJ_CLIENT_SECRET"

server_metadata_url = "https://login.microsoftonline.com/organizations/v2.0/.well-known/openid-configuration"
client_kwargs = { "prompt" = "login" }
